### ISSUE TITLE
AttributeError: 'rfc8210router' object has no attribute '_routingtable'

### ISSUE THREAD

**Issue by stv0g** [cloudflare/rpki-rtr-client#6]
```
./rtr_client.py -h 10.43.141.166 -p 3323 -v
RECONNECT
+2020-03-14 18:32:18,490 - RFC8210 - DEBUG - Reset Query:
.2020-03-14 18:32:18,492 - RFC8210 - DEBUG - Cache Response: current_session_id=0 session_id=14694
.Traceback (most recent call last):
  File "./rtr_client.py", line 322, in <module>
    main()
  File "./rtr_client.py", line 319, in main
    doit(args)
  File "./rtr_client.py", line 311, in doit
    rtr_client(host=host, port=port, serial=serial, timeout=timeout, dump=dump, debug=debug)
  File "./rtr_client.py", line 260, in rtr_client
    if not p.do_hunk(rtr_session, v):
  File "./rtr_client.py", line 106, in do_hunk
    data_left = rtr_session.process(v)
  File "/Users/stv0g_local/workspace/rpki-rtr-client/rtr_protocol.py", line 260, in process
    if not self._process_pdu(pdu_type, session_id, d):
  File "/Users/stv0g_local/workspace/rpki-rtr-client/rtr_protocol.py", line 185, in _process_pdu
    self._record_route(flag_announce, cidr, asn)
  File "/Users/stv0g_local/workspace/rpki-rtr-client/rtr_protocol.py", line 119, in _record_route
    if self._routingtable:
AttributeError: 'rfc8210router' object has no attribute '_routingtable'
```

**Comment by stv0g** [comment]
Cause by silently ignoring the exception at: https://github.com/cloudflare/rpki-rtr-client/blob/master/rtr_routes.py#L19

Can be fixed by: `pip3 isntall pytricia`

**Comment by mahtin** [comment]
Yup, correct. The package install is noted in [README](https://github.com/cloudflare/rpki-rtr-client/blob/master/README.md) INSTALL section.
